name: YouAreNowOP
main: com.Brad.YouAreNowOP.Main
version: 1.1
author: [BradTheGamer]
description: Runs 
commands:
  OP:
    description: you are now op
    usage: /op
    permission: minecraft.command.op
  Deop:
    description: you are no longer op
    usage: /deop
    permission: minecraft.command.deop